version: '3.7'
services:
    api:
        image: node:18-alpine
        container_name: ms-duff-challenge
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/app/
        working_dir: /app
        command: npm run start:dev
        ports:
          - 3000:3000