version: '3.7'
services:
    # api:
    #     image: node:18-alpine3.16
    #     container_name: api
    #     restart: unless-stopped
    #     env_file:
    #         - .env
    #     environment:
    #          DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/mydb?schema=public&connect_timeout=300
    #     volumes:
    #         - .:/app/
    #     working_dir: /app
    #     depends_on:
    #         - postgres
    #     networks:
    #         - my-network
    #     command: npm run start:dev
    #     ports:
    #       - 3000:3000
    postgres:
        image: postgres
        container_name: postgres
        restart: always
        env_file:
            - .env
        environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
        - postgres:/var/lib/postgresql/data
        # networks:
        #     - my-network
        ports:
        - '5454:5432'

# networks:
#   my-network:
#     driver: bridge        

volumes:
  postgres:
